import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, RefreshCw } from "lucide-react";
import CheckOutBillingPage from "./CheckOutBillingPage";
import { CheckOut, getCheckOuts } from "./checkoutsApi";

export default function CheckOutOperationsPage() {
  const [tab, setTab] = useState<"pending" | "completed">("pending"); const [items, setItems] = useState<CheckOut[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setItems(await getCheckOuts()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load checked-out guests."); } finally { setLoading(false); } };
  useEffect(() => { if (tab === "completed") void load(); }, [tab]);
  return <><div className="fo-operation-tabs"><button className={tab === "pending" ? "active" : ""} onClick={() => setTab("pending")}>Pending Check-Outs</button><button className={tab === "completed" ? "active" : ""} onClick={() => setTab("completed")}>Checked Out</button></div>{tab === "pending" ? <CheckOutBillingPage /> : <section className="fo-card fo-reservations-card"><div className="fo-section-heading"><h2>Checked-Out Guests <span className="fo-count">{items.length}</span></h2><button className="fo-outline-button" onClick={() => void load()} disabled={loading}><RefreshCw size={15} />Refresh</button></div>{error && <p className="fo-api-error">{error}</p>}<div className="fo-table-wrap"><table><thead><tr><th>Guest</th><th>Room</th><th>Payment</th><th>Paid via</th><th>Checked out at</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="fo-loading"><LoaderCircle size={18} />Loading checked-out guests…</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="fo-empty">No guests have been checked out yet.</td></tr> : items.map((item) => <tr key={item.id}><td><strong>{item.guest.first_name} {item.guest.last_name}</strong><small>{item.guest.mobile || item.guest.email || "No contact"}</small></td><td>{item.room_number}</td><td><span className="fo-badge success">{item.payment_status}</span></td><td>{item.payment_method.replace("_", " ")}</td><td>{new Date(item.checked_out_at).toLocaleString()}</td><td><span className="fo-badge success"><CheckCircle2 size={12} />Checked out</span></td></tr>)}</tbody></table></div></section>}</>;
}
