import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, RefreshCw, X } from "lucide-react";
import { createCheckOut, getPendingCheckOuts, PendingCheckOut } from "./checkoutsApi";
import { BillingReservation, getBillingReservations } from "./billingApi";

const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(new Date());

export default function CheckOutBillingPage() {
  const [pending, setPending] = useState<PendingCheckOut[]>([]); const [bills, setBills] = useState<BillingReservation[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<PendingCheckOut | null>(null); const [notes, setNotes] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [checkoutData, billingData] = await Promise.all([getPendingCheckOuts(today), getBillingReservations()]); setPending(checkoutData.items); setBills(billingData); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load pending check-outs."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const bill = selected ? bills.find((item) => item.id === selected.id) : undefined;
  const complete = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || bill?.payment_status !== "paid") { setError("The guest bill must be fully paid in Billing before checkout."); return; } setSaving(true); setError(""); try { await createCheckOut(selected.id, "paid", bill.payments[0]?.payment_method || "cash", notes); setSelected(null); setNotes(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to check out this guest."); } finally { setSaving(false); } };
  return <><section className="fo-page-heading"><div><p className="fo-eyebrow">FRONT OFFICE OPERATIONS</p><h2>Check-Out</h2><p>Complete departures after the guest bill is paid.</p></div><button className="fo-outline-button" onClick={() => void load()} disabled={loading}><RefreshCw size={15} />Refresh</button></section><section className="fo-card fo-reservations-card">{error && <p className="fo-api-error">{error}</p>}<div className="fo-section-heading"><h2>Pending Check-Outs <span className="fo-count">{pending.length}</span></h2><span>Departures for {today}</span></div><div className="fo-table-wrap"><table><thead><tr><th>Guest</th><th>Reservation</th><th>Room</th><th>Stay</th><th>Bill</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="fo-loading"><LoaderCircle size={18} />Loading pending check-outs…</td></tr> : pending.length === 0 ? <tr><td colSpan={6} className="fo-empty">No pending check-outs for today.</td></tr> : pending.map((reservation) => { const item = bills.find((entry) => entry.id === reservation.id); const paid = item?.payment_status === "paid"; return <tr key={reservation.id}><td><strong>{reservation.guest.first_name} {reservation.guest.last_name}</strong><small>{reservation.guest.mobile || reservation.guest.email || "No contact information"}</small></td><td>{reservation.reservation_code}</td><td>{reservation.room_number || "Unassigned"}</td><td>{reservation.check_in_date}<small>to {reservation.check_out_date}</small></td><td><span className={`fo-badge ${paid ? "success" : "warning"}`}>{paid ? "Paid" : item?.payment_status || "Unpaid"}</span></td><td><button className="fo-small-button" onClick={() => setSelected(reservation)}>Check-Out</button></td></tr>; })}</tbody></table></div></section>{selected && <div className="fo-modal-backdrop"><form className="fo-modal fo-checkout-modal" onSubmit={complete}><header><div><p className="fo-eyebrow">GUEST DEPARTURE</p><h2>Check out {selected.guest.first_name} {selected.guest.last_name}</h2></div><button type="button" className="fo-icon-button" onClick={() => setSelected(null)} disabled={saving}><X size={19} /></button></header><div className="fo-checkin-summary"><span><CheckCircle2 size={20} /></span><div><strong>{selected.reservation_code}</strong><small>{bill?.payment_status === "paid" ? "Bill fully paid" : "Payment is pending in Billing"}</small></div></div><div className="fo-form-grid"><label className="fo-form-full">Departure notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional notes for this stay" /></label></div><footer><button type="button" className="fo-outline-button" onClick={() => setSelected(null)} disabled={saving}>Cancel</button><button className="fo-button" disabled={saving || bill?.payment_status !== "paid"}>{saving ? <><LoaderCircle size={16} />Checking out…</> : <><CheckCircle2 size={16} />Complete Check-Out</>}</button></footer></form></div>}</>;
}
