import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, RefreshCw } from "lucide-react";
import CheckInPage from "./CheckInPage";
import { CheckIn, getCheckIns } from "./checkinsApi";

export default function CheckInOperationsPage() {
  const [tab, setTab] = useState<"pending" | "completed">("pending"); const [items, setItems] = useState<CheckIn[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setItems(await getCheckIns()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load checked-in guests."); } finally { setLoading(false); } };
  useEffect(() => { if (tab === "completed") void load(); }, [tab]);
  return <><div className="fo-operation-tabs"><button className={tab === "pending" ? "active" : ""} onClick={() => setTab("pending")}>Pending Check-Ins</button><button className={tab === "completed" ? "active" : ""} onClick={() => setTab("completed")}>Checked In</button></div>{tab === "pending" ? <CheckInPage /> : <section className="fo-card fo-reservations-card"><div className="fo-section-heading"><h2>Checked-In Guests <span className="fo-count">{items.length}</span></h2><button className="fo-outline-button" onClick={() => void load()} disabled={loading}><RefreshCw size={15} />Refresh</button></div>{error && <p className="fo-api-error">{error}</p>}<div className="fo-table-wrap"><table><thead><tr><th>Guest</th><th>Room</th><th>Verification</th><th>Document</th><th>Checked in at</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="fo-loading"><LoaderCircle size={18} />Loading checked-in guests…</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="fo-empty">No guests have been checked in yet.</td></tr> : items.map((item) => <tr key={item.id}><td><strong>{item.guest.first_name} {item.guest.last_name}</strong><small>{item.guest.mobile || item.guest.email || "No contact"}</small></td><td>{item.room_number}</td><td><span className={`fo-badge ${item.verification_status === "verified" ? "success" : "warning"}`}>{item.verification_status.replace("_", " ")}</span></td><td>{item.identity_document_type || "—"}</td><td>{new Date(item.checked_in_at).toLocaleString()}</td><td><span className="fo-badge success"><CheckCircle2 size={12} />Checked in</span></td></tr>)}</tbody></table></div></section>}</>;
}
