import { FormEvent, useEffect, useState } from "react";
import { BedDouble, LoaderCircle, RefreshCw, X } from "lucide-react";
import { assignReservationRoom, getReservations, Reservation } from "./reservationsApi";
export default function RoomAssignmentPage() {
  const [reservations, setReservations] = useState<Reservation[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<Reservation | null>(null); const [room, setRoom] = useState(""); const [category, setCategory] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setReservations((await getReservations()).items.filter(r => r.status !== "cancelled")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load room assignments."); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  const open = (r: Reservation) => { setSelected(r); setRoom(r.room_number || ""); setCategory(r.room_category || ""); };
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || !room.trim()) return; setSaving(true); setError(""); try { await assignReservationRoom(selected.id, room.trim(), category.trim()); setSelected(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to assign the room."); } finally { setSaving(false); } };
  return <><section className="fo-page-heading"><div><p className="fo-eyebrow">FRONT OFFICE OPERATIONS</p><h2>Room Assignment</h2><p>Assign rooms to upcoming and in-house reservations.</p></div><button className="fo-outline-button" onClick={() => void load()} disabled={loading}><RefreshCw size={15}/>Refresh</button></section><section className="fo-card fo-reservations-card">{error && <p className="fo-api-error">{error}</p>}<div className="fo-section-heading"><h2>Room Allocations <span className="fo-count">{reservations.length}</span></h2><span>Live property data</span></div><div className="fo-table-wrap"><table><thead><tr>{["Guest","Reservation ID","Stay","Room","Status","Action"].map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={6} className="fo-loading"><LoaderCircle size={18}/>Loading room assignments…</td></tr> : reservations.length === 0 ? <tr><td colSpan={6} className="fo-empty">No reservations available.</td></tr> : reservations.map(r => <tr key={r.id}><td><strong>{r.guest.first_name} {r.guest.last_name}</strong><small>{r.guest.mobile || r.guest.email || "No contact information"}</small></td><td>{r.reservation_code}</td><td>{r.check_in_date}<small>to {r.check_out_date}</small></td><td>{r.room_number || "Unassigned"}<small>{r.room_category || ""}</small></td><td><span className={`fo-badge ${r.status === "cancelled" ? "warning" : "success"}`}>{r.status}</span></td><td><button className="fo-small-button" onClick={() => open(r)}><BedDouble size={14}/>{r.room_number ? "Change Room" : "Assign Room"}</button></td></tr>)}</tbody></table></div></section>{selected && <div className="fo-modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget && !saving) setSelected(null); }}><form className="fo-modal" onSubmit={save}><header><div><p className="fo-eyebrow">ROOM ASSIGNMENT</p><h2>{selected.room_number ? "Change room" : "Assign a room"}</h2></div><button type="button" className="fo-icon-button" disabled={saving} onClick={() => setSelected(null)} aria-label="Close"><X size={19}/></button></header><div className="fo-checkin-summary"><span><BedDouble size={20}/></span><div><strong>{selected.guest.first_name} {selected.guest.last_name}</strong><small>{selected.reservation_code} · {selected.check_in_date} to {selected.check_out_date}</small></div></div><div className="fo-form-grid"><label>Room number<input required value={room} placeholder="Example: 101" onChange={event => setRoom(event.target.value)}/></label><label>Room category<input value={category} placeholder="Example: Deluxe" onChange={event => setCategory(event.target.value)}/></label></div>{error && <p className="fo-api-error">{error}</p>}<footer><button type="button" className="fo-outline-button" disabled={saving} onClick={() => setSelected(null)}>Cancel</button><button className="fo-button" disabled={saving}>{saving ? <><LoaderCircle size={16}/>Saving…</> : <><BedDouble size={16}/>Save Room</>}</button></footer></form></div>}</>;
}

